config/routes.rb
Rails.application.routes.draw do
	root 'statics#home'
	match '/register', to: 'authentication#register', via: 'get'
	match '/register', to: 'authentication#create', via: 'post'
	match '/login', to: 'authentication#login', via: ['get','post']
	match '/logout', to: 'authentication#destroy', via: 'delete'
	match '/upload', to: 'image#upload', via: 'get'	
	match '/image/edit/:id', to: 'image#edit', via: 'get'	
	match '/image/edit/:id', to: 'image#edit_post', via: 'patch'
	match '/upload', to: 'image#upload_post', via: 'post'	
	match '/uploads/:id.(:size.):ext', to: 'image#fetch', via: 'get'
	match '/user/:userName/edit', to: 'authentication#edit', via: 'get', as: 'user_edit'
	match '/user/:userName/edit', to: 'authentication#update', via: 'patch'
	match '/image/:id', to: 'image#show', via: 'get'	
	match '/shared(/:start)',to:'image#shared', via:'get'
	match '/image/delete/:id', to: 'image#delete', via: 'delete'
	match '/photos(/:start)', to: 'image#mine', via: 'get'
	
	match '/user/:userName', to: 'authentication#profile', via: 'get'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :image_versions, dependent: :destroy
  has_many :permissions, dependent: :destroy
  
  def can_view?(user)
  	self.permissions.find_by(level:2) || (user && self.user==user || self.permissions.find_by(level:1,user_id:user.id))
  end
  def path
  	"/uploads/#{self.id}#{self.image_versions.last.ext}"
  end
  def thumb
  	"/uploads/#{self.id}.thumb#{self.image_versions.last.ext}"
	end  	
  def current_version(version=nil)
  	self.image_versions.last.store_url(version)
  end
  def description
  	self.image_versions.last.description
  end
  
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
	skip_before_action :require_login, only: [:fetch,:show]

	def upload
			@image=Image.new
			@image_version=@image.image_versions.new
	end
	
	def upload_post
		@image=current_user.images.new()
		@image_version=@image.image_versions.new(params.require(:image_version).permit(:store,:description))
		
		perms=params.require(:permission).permit(:level)
		level=perms[:level].to_i
		if level && level == 0
			@image.permissions.destroy_all
		elsif level && level==1
			params[:permission][:users].split(',').each do |userToken|
				userToken=userToken.strip
				user=User.find_by(userName:userToken.strip)
				user||=User.find_by(email:userToken)
				if user
					perm=@image.permissions.new()
					perm.user_id=user.id
					perm.level=1
				end
				perm.save
			end
		elsif level && level==2
			perm=@image.permissions.find_by_level(2)
			@image.permissions.create(level:2) if perm.nil?
		end

		if @image.save
			redirect_to "/image/#{@image.id}"
		else
			redirect_to '/upload'
		end
	end
	
	def fetch
		image=Image.find(params[:id])
		if image.can_view?(current_user)
			send_file(image.current_version(params[:size]),disposition: 'inline')
		else
			render('statics/noperm')
		end
	end
	
	def show		
		@image=Image.find_by_id(params[:id])
		
		if !(@image && @image.can_view?(current_user))
			render('statics/noperm')
		end
	end
	
	def mine
		if params[:start]
			offset=(params[:start].to_i-1)*10
		else
			offset=0
		end
		@images=current_user.images.offset(offset).limit(10)
	end
	def shared
		if params[:start]
			offset=(params[:start].to_i-1)*10
		else
			offset=0
		end
		@shared=Permission.where(user_id:current_user.id,level:1).offset(offset).limit(10)
	end
	def edit
		@image=Image.find_by_id(params[:id])
		@perm=@image.permissions.last.level if @image.permissions.last
		if !(@image && @image.user==current_user)
			redirect_to "/image/#{params[:id]}"
		end
	end
	def edit_post
		@image=Image.find_by_id(params[:id])
		
		level=params[:permission][:level].to_i || nil
		edits=params.require(:edit).permit(:rotate)
		if edits[:rotate].to_i>0
			magick=MiniMagick::Image.open(@image.current_version)
			magick.rotate edits[:rotate]
			version||=@image.image_versions.new
			version.store=File.new(magick.path)
		end
		version||=@image.image_versions.last
		version.update_attributes(params.require(:image).permit(:description))
		
		if level && level == 0
			@image.permissions.destroy_all
		elsif level && level==1
			params[:permission][:users].split(',').each do |userToken|
				userToken=userToken.strip
				user=User.find_by(userName:userToken.strip)
				user||=User.find_by(email:userToken)
				if user
					perm=@image.permissions.new()
					perm.user_id=user.id
					perm.level=1
				end
				perm.save
			end
		elsif level && level==2
			perm=@image.permissions.find_by_level(2)
			@image.permissions.create(level:2) if perm.nil?
		end
		
		if @image.save
			flash[:success]="Image updated"
			redirect_to "/image/#{@image.id}"
		else
			render 'upload'
		end
	end
	def delete
		@image=Image.find_by_id(params[:id])
		if @image && @image.user=current_user
			@image.destroy
			flash[:success]="Image deleted"
		end
		redirect_to '/photos'
	end
end

app/helpers/image_helper.rb
module ImageHelper

	def prev_link
		page=1
		if params[:start] && params[:start].to_i>1
			page+=params[:start].to_i/10
			link_to "<<Previous" , "/photos/#{page}"
		end
	end
	def next_link
		if page=params[:start]
			page=page.to_i
		else
			page=1
		end
		render text:'<pre>'.html_safe
		render text:"#{page*10}\n"
		render text:"#{current_user.images.count}"
		render text:'</pre>'.html_safe
		if page*10<current_user.images.count
			link_to "next>>" , "/photos/#{page+1}"
		end
	end
	def img_link(image,options=nil)
		if options[:size]
			path=image.thumb
		else
			path=image.path
		end
		link_to image_tag(path), "/image/#{image.id}"
	end
end

app/views/image/all.html.erb
<% @iamges.

app/views/image/edit.html.erb
<div class="container" style="width:30%">
<%= form_for @image, url: "/image/edit/#{@image.id}", :html => {:class => "form-horizontal", role:"form", multipart: true  } do |f| %>
<h2>Edit Image</h2>
<%= image_tag @image.path %>
<div class="form-group">
<%= f.label :store, "Filters:" %> 
<label>Rotate: </label><%= select 'edit','rotate',{'None' =>0,'Clockwise (90)'=>90, 'Upside down (180)'=>180, 'Counter clockwise (270)'=>270} %>
<!-- Don't know what type of controls to add here for the filters.-->
</div>
<div class="form-group">
<%= f.label :store, "Description:" %><%= f.text_area :description, class:"form-control"  %><br />
</div>
<div class="form-group">
<%= f.label :store, "Permission:" %> <br />
<%= select 'permission', 'level',{Private:0,Shared:1,Public:2},{id:'permissionselect', selected:@perm.to_s}, onchange:'var perms=$("#permissionbox");if ($(this).val
()==1){perms.show()}else{perms.hide();}' %> <br/>
<div id="permissionbox" style="display:none">
<label>Usernames:</label><input type="text" name="permission[users]"/>
</div>
</div>
<div class="form-group">
<%= f.submit "Save", class: "btn btn-lg btn-primary" %>
</div>
<% end %>
<%= link_to "delete image", "/image/delete/#{@image.id}",method: :delete,class: "btn btn-lg btn-danger" %>
</div>

app/views/image/mine.html.erb
<%= link_to "Upload image", upload_path %><br />
<% if @images %>
<% @images.each do |img| %>
<%= img_link img, size: "thumb" %>
<% end %>
<% end %>

<%= prev_link %>
<%= next_link %>

app/views/image/shared.html.erb
<% if @shared %>
<% @shared.each do |perm| %>
<%= img_link(perm.image,size:'thumb') %>
<% end %>
<% end %>

<%= prev_link %>
<%= next_link %>

app/views/image/show.html.erb
<% if @image.user==current_user %>
<%= link_to "edit image", "/image/edit/#{@image.id}" %><br />
<% end %>
<%= image_tag @image.path %>
	
<div class="description">
<%= @image.description %>
</div>

app/views/image/upload.html.erb
<div class="container" style="width:30%">
<% if @image_version.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">The form contains <%= pluralize(@user.errors.count, "error") %>.</div>
		<ul>
			<% @image.errors.full_messages.each do |msg| %>
	    	<li>* <%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

<%= form_for @image_version, url: upload_path, :html => {:class => "form-horizontal", role:"form", multipart: true  } do |f| %>
<h2>Upload Image</h2>
<div class="form-group">
<%= f.label :store, "Select Image:" %><%= f.file_field :store %>
</div>
<div class="form-group">
<%= f.label :description, "Description:" %><%= f.text_area :description, class:"form-control"  %><br />
</div>
<div class="form-group">
<%= f.label :store, "Permission:" %> <br />
<%= select 'permission', 'level',{Private:0,Shared:1,Public:2},{id:'permissionselect'}, onchange:'var perms=$("#permissionbox");if ($(this).val()==1){perms.show()}else{perms.hide();}' %> <br/>
<div id="permissionbox" style="display:none">
<label>Usernames:</label><input type="text" name="permission[users]"/>
</div></div>
<div class="form-group">
<%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
</div>
<% end %>
</div>