config/routes.rb
Rails.application.routes.draw do
	root 'statics#home'
	match '/register', to: 'authentication#register', via: 'get'
	match '/register', to: 'authentication#create', via: 'post'
	match '/login', to: 'authentication#login', via: ['get','post']
	match '/logout', to: 'authentication#destroy', via: 'delete'
	match '/upload', to: 'image#upload', via: 'get'	
	match '/image/edit/:id', to: 'image#edit', via: 'get'	
	match '/image/edit/:id', to: 'image#edit_post', via: 'patch'
	match '/upload', to: 'image#upload_post', via: 'post'	
	match '/uploads/:id.(:size.):ext', to: 'image#fetch', via: 'get'
	match '/user/:userName/edit', to: 'authentication#edit', via: 'get', as: 'user_edit'
	match '/user/:userName/edit', to: 'authentication#update', via: 'patch'
	match '/image/:id', to: 'image#show', via: 'get'	
	match '/shared(/:start)',to:'image#shared', via:'get'
	match '/image/delete/:id', to: 'image#delete', via: 'delete'
	match '/photos(/:start)', to: 'image#mine', via: 'get'
	
	match '/user/:userName', to: 'authentication#profile', via: 'get'

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	skip_before_action :require_login, except: [:profile,:edit]
	#register user
  def register
  	@user=User.new
  end

	#save new user
  def create
  	@user=User.new(user_params)
  	if @user.save
  		login_user @user
  		flash[:success] = "Thanks for joining #{@user.firstName}!"
  		redirect_to "/user/#{@user.userName}"
  	else
  		render 'register'
  	end
  end

#display user profile
  def profile
  	@user=User.find_by_userName(params[:userName])
  	if @user.nil?
  		render 'nouser'
  	end
  end

#login/display form
  def login
  	if params[:session]
  		(user=User.find_by_email(params[:session][:token].downcase) || user=User.find_by_userName(params[:session][:token]))
  		if user && user.authenticate(params[:session][:password])
				login_user user
				flash[:success]= "Welcome back #{user.firstName}!"
	  		redirect_to "/user/#{user.userName}"
  		else
  			flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
  			render 'login'
  		end
  	end
  end
  
#logout
	def destroy
		logout
		redirect_to root_url  
	end

#edit user
	def edit
		@user=current_user
	end
# commit edit
	def update
		@user=current_user
		password=params[:user][:current_password]
		if password && @user.authenticate(password)
			if @user.update_attributes(update_params)
				flash[:success] = "Details updated"
				redirect_to "/user/#{@user.userName}"
			else
				render 'edit'
			end
		else
		#current_user.update_attributes
			@user.errors.add(:current_password,'incorrect!')
			render 'edit'
		end
	end
	
	private
  def user_params
  	params.require(:user).permit(:firstName,:lastName,:email,:userName,:password,:password_confirmation)
  end
  def update_params
  	params.require(:user).permit(:firstName,:lastName,:email,:userName,:password,:password_confirmation)
  end

end

app/helpers/authentication_helper.rb
module AuthenticationHelper

	def login_user(user)
		remember user
		session[:user_id] = user.id
	end
	def remember(user)
		user.rememberMe
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:authToken] = user.authToken
	end
	def logout
		current_user.forgetMe
		cookies.delete(:user_id)
		cookies.delete(:authToken)
		session.delete(:user_id)
		@current_user=nil
	end
	def current_user
		if (user_id=session[:user_id])
			@current_user ||=User.find_by_id session[:user_id]
		elsif (user_id=cookies.signed[:user_id])
			user=User.find_by_id(user_id)
			if user && user.authed?(cookies[:authToken])
				login_user user
				@current_user = user
			end
		end
	end
	def logged_in?
		!current_user.nil?
	end
	def edit_profile_link(user)
		if logged_in? && user==current_user
			link_to "edit profile", "/user/#{user.userName}/edit"
		end
	end	
end

app/views/authentication/edit.html.erb
<h1><%= image_tag @user.gravatar_image %><%= @user.userName %></h1>
<p><%= link_to "change image", 'http://en.gravatar.com/support/what-is-gravatar/' ,target:'new'%>

<%= form_for @user, url: user_edit_path, method: 'patch' do |f| %>
<%= render 'shared/error_messages' %>
<%= f.label :firstName, 'First Name:' %> <%= f.text_field :firstName %><br />
Last Name: <%= f.text_field :lastName %><br />
Email Address: <%= f.text_field :email %><br />
<%= f.label :current_password,'Current Password:' %> <%= f.password_field :current_password %><br />
Password: <%= f.password_field :password %><br/>
Confirmation:<%= f.password_field :password_confirmation %><br />
<%= f.submit %>
<% end %>

app/views/authentication/login.html.erb
<% provide(:title, "Sign in") %>


<div class="container" style="width:30%;">
 <div class="span6 offset3" >
    
    
    
        <%= form_for(:session, url: login_path, :html => {:class => "form-signin", role:"form"}) do |f| %>
        <h2 class="form-signin-heading">Sign In</h2>
          <%= f.label :token, "Username/Email" %>
          <%= f.text_field :token, class: "form-control", :autofocus =>true   %>
          <%= f.label :password %>
          <%= f.password_field :password, class:"form-control" %> <br/>
          <%= f.submit "Sign in", class: "btn btn-lg btn-primary btn-block" %>
          <% end %>
    
    <p>New user? <%= link_to "Register now!", register_path %></p>
  </div>
</div>

app/views/authentication/nouser.html.erb
No user with that username

app/views/authentication/profile.html.erb
<h1>
	<img src="<%= @user.gravatar_image %>" />
	<%= @user.firstName %>
	<%= @user.lastName %>
</h1>
<%= edit_profile_link @user %>

app/views/authentication/register.html.erb
<div class="container" style="max-width:800px">
<%= form_for @user, url: register_path, :html => {:class => "form-signin", role:"form"} do |f| %>
<h1>Register</h1>
<%= render 'shared/error_messages' %>
First Name: <%= f.text_field :firstName, class:"form-control" %><br/>
Last Name: <%= f.text_field :lastName, class:"form-control" %><br />
User Name: <%= f.text_field :userName, class:"form-control" %><br />
Email Address: <%= f.text_field :email, class:"form-control" %><br />
Password: <%= f.password_field :password, class:"form-control" %><br/>
Confirmation:<%= f.password_field :password_confirmation, class:"form-control" %><br />
<%= f.submit "Register", class: "btn btn-lg btn-primary btn-block" %>
<% end %>
</div>