config/routes.rb
Rails.application.routes.draw do
	root 'statics#home'
	match '/register', to: 'authentication#register', via: 'get'
	match '/register', to: 'authentication#create', via: 'post'
	match '/login', to: 'authentication#login', via: ['get','post']
	match '/logout', to: 'authentication#destroy', via: 'delete'
	match '/upload', to: 'image#upload', via: 'get'	
	match '/image/edit/:id', to: 'image#edit', via: 'get'	
	match '/image/edit/:id', to: 'image#edit_post', via: 'patch'
	match '/upload', to: 'image#upload_post', via: 'post'	
	match '/uploads/:id.(:size.):ext', to: 'image#fetch', via: 'get'
	match '/user/:userName/edit', to: 'authentication#edit', via: 'get', as: 'user_edit'
	match '/user/:userName/edit', to: 'authentication#update', via: 'patch'
	match '/image/:id', to: 'image#show', via: 'get'	
	match '/shared(/:start)',to:'image#shared', via:'get'
	match '/image/delete/:id', to: 'image#delete', via: 'delete'
	match '/photos(/:start)', to: 'image#mine', via: 'get'
	
	match '/user/:userName', to: 'authentication#profile', via: 'get'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "image magik", root_path, id: "logo",class:"navbar-brand" %>
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<nav class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<% if logged_in? %>
					<li><%= link_to 'shared', "/shared/1" %></li>
					<li><%= link_to 'photos', "/photos/1" %></li>
					<li><%= link_to "profile", "/user/#{current_user.userName}" %></li>
					<li><%= link_to "logout", logout_path, method: 'delete' %></li>
				<% else %>
					<li><%= link_to "login", login_path %></li>
					<li><%= link_to "Register", register_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageMagik | <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
                    
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>